// Generated by ProtoGen, Version=2.4.1.555, Culture=neutral, PublicKeyToken=55f7125234beb589.  DO NOT EDIT!
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.ProtocolBuffers;
using pbc = global::Google.ProtocolBuffers.Collections;
using pbd = global::Google.ProtocolBuffers.Descriptors;
using scg = global::System.Collections.Generic;
namespace libsignal.fingerprint {
  
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public static partial class FingerprintProtos {
  
    #region Extension registration
    public static void RegisterAllExtensions(pb::ExtensionRegistry registry) {
    }
    #endregion
    #region Static variables
    private static pbd::MessageDescriptor internal__static_LogicalFingerprint__Descriptor;
    private static pb::FieldAccess.FieldAccessorTable<global::libsignal.fingerprint.FingerprintProtos.LogicalFingerprint, global::libsignal.fingerprint.FingerprintProtos.LogicalFingerprint.Builder> internal__static_LogicalFingerprint__FieldAccessorTable;
    private static pbd::MessageDescriptor internal__static_CombinedFingerprints__Descriptor;
    private static pb::FieldAccess.FieldAccessorTable<global::libsignal.fingerprint.FingerprintProtos.CombinedFingerprints, global::libsignal.fingerprint.FingerprintProtos.CombinedFingerprints.Builder> internal__static_CombinedFingerprints__FieldAccessorTable;
    #endregion
    #region Descriptor
    public static pbd::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbd::FileDescriptor descriptor;
    
    static FingerprintProtos() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChlGaW5nZXJwcmludFByb3RvY29sLnByb3RvIiUKEkxvZ2ljYWxGaW5nZXJw", 
            "cmludBIPCgdjb250ZW50GAEgASgMIoYBChRDb21iaW5lZEZpbmdlcnByaW50", 
            "cxIPCgd2ZXJzaW9uGAEgASgNEi0KEGxvY2FsRmluZ2VycHJpbnQYAiABKAsy", 
            "Ey5Mb2dpY2FsRmluZ2VycHJpbnQSLgoRcmVtb3RlRmluZ2VycHJpbnQYAyAB", 
          "KAsyEy5Mb2dpY2FsRmluZ2VycHJpbnQ="));
      pbd::FileDescriptor.InternalDescriptorAssigner assigner = delegate(pbd::FileDescriptor root) {
        descriptor = root;
        internal__static_LogicalFingerprint__Descriptor = Descriptor.MessageTypes[0];
        internal__static_LogicalFingerprint__FieldAccessorTable = 
            new pb::FieldAccess.FieldAccessorTable<global::libsignal.fingerprint.FingerprintProtos.LogicalFingerprint, global::libsignal.fingerprint.FingerprintProtos.LogicalFingerprint.Builder>(internal__static_LogicalFingerprint__Descriptor,
                new string[] { "Content", });
        internal__static_CombinedFingerprints__Descriptor = Descriptor.MessageTypes[1];
        internal__static_CombinedFingerprints__FieldAccessorTable = 
            new pb::FieldAccess.FieldAccessorTable<global::libsignal.fingerprint.FingerprintProtos.CombinedFingerprints, global::libsignal.fingerprint.FingerprintProtos.CombinedFingerprints.Builder>(internal__static_CombinedFingerprints__Descriptor,
                new string[] { "Version", "LocalFingerprint", "RemoteFingerprint", });
        return null;
      };
      pbd::FileDescriptor.InternalBuildGeneratedFileFrom(descriptorData,
          new pbd::FileDescriptor[] {
          }, assigner);
    }
    #endregion
    
    #region Messages
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public sealed partial class LogicalFingerprint : pb::GeneratedMessage<LogicalFingerprint, LogicalFingerprint.Builder> {
      private LogicalFingerprint() { }
      private static readonly LogicalFingerprint defaultInstance = new LogicalFingerprint().MakeReadOnly();
      private static readonly string[] _logicalFingerprintFieldNames = new string[] { "content" };
      private static readonly uint[] _logicalFingerprintFieldTags = new uint[] { 10 };
      public static LogicalFingerprint DefaultInstance {
        get { return defaultInstance; }
      }
      
      public override LogicalFingerprint DefaultInstanceForType {
        get { return DefaultInstance; }
      }
      
      protected override LogicalFingerprint ThisMessage {
        get { return this; }
      }
      
      public static pbd::MessageDescriptor Descriptor {
        get { return global::libsignal.fingerprint.FingerprintProtos.internal__static_LogicalFingerprint__Descriptor; }
      }
      
      protected override pb::FieldAccess.FieldAccessorTable<LogicalFingerprint, LogicalFingerprint.Builder> InternalFieldAccessors {
        get { return global::libsignal.fingerprint.FingerprintProtos.internal__static_LogicalFingerprint__FieldAccessorTable; }
      }
      
      public const int ContentFieldNumber = 1;
      private bool hasContent;
      private pb::ByteString content_ = pb::ByteString.Empty;
      public bool HasContent {
        get { return hasContent; }
      }
      public pb::ByteString Content {
        get { return content_; }
      }
      
      public override bool IsInitialized {
        get {
          return true;
        }
      }
      
      public override void WriteTo(pb::ICodedOutputStream output) {
        CalcSerializedSize();
        string[] field_names = _logicalFingerprintFieldNames;
        if (hasContent) {
          output.WriteBytes(1, field_names[0], Content);
        }
        UnknownFields.WriteTo(output);
      }
      
      private int memoizedSerializedSize = -1;
      public override int SerializedSize {
        get {
          int size = memoizedSerializedSize;
          if (size != -1) return size;
          return CalcSerializedSize();
        }
      }
      
      private int CalcSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;
        
        size = 0;
        if (hasContent) {
          size += pb::CodedOutputStream.ComputeBytesSize(1, Content);
        }
        size += UnknownFields.SerializedSize;
        memoizedSerializedSize = size;
        return size;
      }
      public static LogicalFingerprint ParseFrom(pb::ByteString data) {
        return ((Builder) CreateBuilder().MergeFrom(data)).BuildParsed();
      }
      public static LogicalFingerprint ParseFrom(pb::ByteString data, pb::ExtensionRegistry extensionRegistry) {
        return ((Builder) CreateBuilder().MergeFrom(data, extensionRegistry)).BuildParsed();
      }
      public static LogicalFingerprint ParseFrom(byte[] data) {
        return ((Builder) CreateBuilder().MergeFrom(data)).BuildParsed();
      }
      public static LogicalFingerprint ParseFrom(byte[] data, pb::ExtensionRegistry extensionRegistry) {
        return ((Builder) CreateBuilder().MergeFrom(data, extensionRegistry)).BuildParsed();
      }
      public static LogicalFingerprint ParseFrom(global::System.IO.Stream input) {
        return ((Builder) CreateBuilder().MergeFrom(input)).BuildParsed();
      }
      public static LogicalFingerprint ParseFrom(global::System.IO.Stream input, pb::ExtensionRegistry extensionRegistry) {
        return ((Builder) CreateBuilder().MergeFrom(input, extensionRegistry)).BuildParsed();
      }
      public static LogicalFingerprint ParseDelimitedFrom(global::System.IO.Stream input) {
        return CreateBuilder().MergeDelimitedFrom(input).BuildParsed();
      }
      public static LogicalFingerprint ParseDelimitedFrom(global::System.IO.Stream input, pb::ExtensionRegistry extensionRegistry) {
        return CreateBuilder().MergeDelimitedFrom(input, extensionRegistry).BuildParsed();
      }
      public static LogicalFingerprint ParseFrom(pb::ICodedInputStream input) {
        return ((Builder) CreateBuilder().MergeFrom(input)).BuildParsed();
      }
      public static LogicalFingerprint ParseFrom(pb::ICodedInputStream input, pb::ExtensionRegistry extensionRegistry) {
        return ((Builder) CreateBuilder().MergeFrom(input, extensionRegistry)).BuildParsed();
      }
      private LogicalFingerprint MakeReadOnly() {
        return this;
      }
      
      public static Builder CreateBuilder() { return new Builder(); }
      public override Builder ToBuilder() { return CreateBuilder(this); }
      public override Builder CreateBuilderForType() { return new Builder(); }
      public static Builder CreateBuilder(LogicalFingerprint prototype) {
        return new Builder(prototype);
      }
      
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
      public sealed partial class Builder : pb::GeneratedBuilder<LogicalFingerprint, Builder> {
        protected override Builder ThisBuilder {
          get { return this; }
        }
        public Builder() {
          result = DefaultInstance;
          resultIsReadOnly = true;
        }
        internal Builder(LogicalFingerprint cloneFrom) {
          result = cloneFrom;
          resultIsReadOnly = true;
        }
        
        private bool resultIsReadOnly;
        private LogicalFingerprint result;
        
        private LogicalFingerprint PrepareBuilder() {
          if (resultIsReadOnly) {
            LogicalFingerprint original = result;
            result = new LogicalFingerprint();
            resultIsReadOnly = false;
            MergeFrom(original);
          }
          return result;
        }
        
        public override bool IsInitialized {
          get { return result.IsInitialized; }
        }
        
        protected override LogicalFingerprint MessageBeingBuilt {
          get { return PrepareBuilder(); }
        }
        
        public override Builder Clear() {
          result = DefaultInstance;
          resultIsReadOnly = true;
          return this;
        }
        
        public override Builder Clone() {
          if (resultIsReadOnly) {
            return new Builder(result);
          } else {
            return new Builder().MergeFrom(result);
          }
        }
        
        public override pbd::MessageDescriptor DescriptorForType {
          get { return global::libsignal.fingerprint.FingerprintProtos.LogicalFingerprint.Descriptor; }
        }
        
        public override LogicalFingerprint DefaultInstanceForType {
          get { return global::libsignal.fingerprint.FingerprintProtos.LogicalFingerprint.DefaultInstance; }
        }
        
        public override LogicalFingerprint BuildPartial() {
          if (resultIsReadOnly) {
            return result;
          }
          resultIsReadOnly = true;
          return result.MakeReadOnly();
        }
        
        public override Builder MergeFrom(pb::IMessage other) {
          if (other is LogicalFingerprint) {
            return MergeFrom((LogicalFingerprint) other);
          } else {
            base.MergeFrom(other);
            return this;
          }
        }
        
        public override Builder MergeFrom(LogicalFingerprint other) {
          if (other == global::libsignal.fingerprint.FingerprintProtos.LogicalFingerprint.DefaultInstance) return this;
          PrepareBuilder();
          if (other.HasContent) {
            Content = other.Content;
          }
          this.MergeUnknownFields(other.UnknownFields);
          return this;
        }
        
        public override Builder MergeFrom(pb::ICodedInputStream input) {
          return MergeFrom(input, pb::ExtensionRegistry.Empty);
        }
        
        public override Builder MergeFrom(pb::ICodedInputStream input, pb::ExtensionRegistry extensionRegistry) {
          PrepareBuilder();
          pb::UnknownFieldSet.Builder unknownFields = null;
          uint tag;
          string field_name;
          while (input.ReadTag(out tag, out field_name)) {
            if(tag == 0 && field_name != null) {
              int field_ordinal = global::System.Array.BinarySearch(_logicalFingerprintFieldNames, field_name, global::System.StringComparer.Ordinal);
              if(field_ordinal >= 0)
                tag = _logicalFingerprintFieldTags[field_ordinal];
              else {
                if (unknownFields == null) {
                  unknownFields = pb::UnknownFieldSet.CreateBuilder(this.UnknownFields);
                }
                ParseUnknownField(input, unknownFields, extensionRegistry, tag, field_name);
                continue;
              }
            }
            switch (tag) {
              case 0: {
                throw pb::InvalidProtocolBufferException.InvalidTag();
              }
              default: {
                if (pb::WireFormat.IsEndGroupTag(tag)) {
                  if (unknownFields != null) {
                    this.UnknownFields = unknownFields.Build();
                  }
                  return this;
                }
                if (unknownFields == null) {
                  unknownFields = pb::UnknownFieldSet.CreateBuilder(this.UnknownFields);
                }
                ParseUnknownField(input, unknownFields, extensionRegistry, tag, field_name);
                break;
              }
              case 10: {
                result.hasContent = input.ReadBytes(ref result.content_);
                break;
              }
            }
          }
          
          if (unknownFields != null) {
            this.UnknownFields = unknownFields.Build();
          }
          return this;
        }
        
        
        public bool HasContent {
          get { return result.hasContent; }
        }
        public pb::ByteString Content {
          get { return result.Content; }
          set { SetContent(value); }
        }
        public Builder SetContent(pb::ByteString value) {
          pb::ThrowHelper.ThrowIfNull(value, "value");
          PrepareBuilder();
          result.hasContent = true;
          result.content_ = value;
          return this;
        }
        public Builder ClearContent() {
          PrepareBuilder();
          result.hasContent = false;
          result.content_ = pb::ByteString.Empty;
          return this;
        }
      }
      static LogicalFingerprint() {
        object.ReferenceEquals(global::libsignal.fingerprint.FingerprintProtos.Descriptor, null);
      }
    }
    
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public sealed partial class CombinedFingerprints : pb::GeneratedMessage<CombinedFingerprints, CombinedFingerprints.Builder> {
      private CombinedFingerprints() { }
      private static readonly CombinedFingerprints defaultInstance = new CombinedFingerprints().MakeReadOnly();
      private static readonly string[] _combinedFingerprintsFieldNames = new string[] { "localFingerprint", "remoteFingerprint", "version" };
      private static readonly uint[] _combinedFingerprintsFieldTags = new uint[] { 18, 26, 8 };
      public static CombinedFingerprints DefaultInstance {
        get { return defaultInstance; }
      }
      
      public override CombinedFingerprints DefaultInstanceForType {
        get { return DefaultInstance; }
      }
      
      protected override CombinedFingerprints ThisMessage {
        get { return this; }
      }
      
      public static pbd::MessageDescriptor Descriptor {
        get { return global::libsignal.fingerprint.FingerprintProtos.internal__static_CombinedFingerprints__Descriptor; }
      }
      
      protected override pb::FieldAccess.FieldAccessorTable<CombinedFingerprints, CombinedFingerprints.Builder> InternalFieldAccessors {
        get { return global::libsignal.fingerprint.FingerprintProtos.internal__static_CombinedFingerprints__FieldAccessorTable; }
      }
      
      public const int VersionFieldNumber = 1;
      private bool hasVersion;
      private uint version_;
      public bool HasVersion {
        get { return hasVersion; }
      }
      [global::System.CLSCompliant(false)]
      public uint Version {
        get { return version_; }
      }
      
      public const int LocalFingerprintFieldNumber = 2;
      private bool hasLocalFingerprint;
      private global::libsignal.fingerprint.FingerprintProtos.LogicalFingerprint localFingerprint_;
      public bool HasLocalFingerprint {
        get { return hasLocalFingerprint; }
      }
      public global::libsignal.fingerprint.FingerprintProtos.LogicalFingerprint LocalFingerprint {
        get { return localFingerprint_ ?? global::libsignal.fingerprint.FingerprintProtos.LogicalFingerprint.DefaultInstance; }
      }
      
      public const int RemoteFingerprintFieldNumber = 3;
      private bool hasRemoteFingerprint;
      private global::libsignal.fingerprint.FingerprintProtos.LogicalFingerprint remoteFingerprint_;
      public bool HasRemoteFingerprint {
        get { return hasRemoteFingerprint; }
      }
      public global::libsignal.fingerprint.FingerprintProtos.LogicalFingerprint RemoteFingerprint {
        get { return remoteFingerprint_ ?? global::libsignal.fingerprint.FingerprintProtos.LogicalFingerprint.DefaultInstance; }
      }
      
      public override bool IsInitialized {
        get {
          return true;
        }
      }
      
      public override void WriteTo(pb::ICodedOutputStream output) {
        CalcSerializedSize();
        string[] field_names = _combinedFingerprintsFieldNames;
        if (hasVersion) {
          output.WriteUInt32(1, field_names[2], Version);
        }
        if (hasLocalFingerprint) {
          output.WriteMessage(2, field_names[0], LocalFingerprint);
        }
        if (hasRemoteFingerprint) {
          output.WriteMessage(3, field_names[1], RemoteFingerprint);
        }
        UnknownFields.WriteTo(output);
      }
      
      private int memoizedSerializedSize = -1;
      public override int SerializedSize {
        get {
          int size = memoizedSerializedSize;
          if (size != -1) return size;
          return CalcSerializedSize();
        }
      }
      
      private int CalcSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;
        
        size = 0;
        if (hasVersion) {
          size += pb::CodedOutputStream.ComputeUInt32Size(1, Version);
        }
        if (hasLocalFingerprint) {
          size += pb::CodedOutputStream.ComputeMessageSize(2, LocalFingerprint);
        }
        if (hasRemoteFingerprint) {
          size += pb::CodedOutputStream.ComputeMessageSize(3, RemoteFingerprint);
        }
        size += UnknownFields.SerializedSize;
        memoizedSerializedSize = size;
        return size;
      }
      public static CombinedFingerprints ParseFrom(pb::ByteString data) {
        return ((Builder) CreateBuilder().MergeFrom(data)).BuildParsed();
      }
      public static CombinedFingerprints ParseFrom(pb::ByteString data, pb::ExtensionRegistry extensionRegistry) {
        return ((Builder) CreateBuilder().MergeFrom(data, extensionRegistry)).BuildParsed();
      }
      public static CombinedFingerprints ParseFrom(byte[] data) {
        return ((Builder) CreateBuilder().MergeFrom(data)).BuildParsed();
      }
      public static CombinedFingerprints ParseFrom(byte[] data, pb::ExtensionRegistry extensionRegistry) {
        return ((Builder) CreateBuilder().MergeFrom(data, extensionRegistry)).BuildParsed();
      }
      public static CombinedFingerprints ParseFrom(global::System.IO.Stream input) {
        return ((Builder) CreateBuilder().MergeFrom(input)).BuildParsed();
      }
      public static CombinedFingerprints ParseFrom(global::System.IO.Stream input, pb::ExtensionRegistry extensionRegistry) {
        return ((Builder) CreateBuilder().MergeFrom(input, extensionRegistry)).BuildParsed();
      }
      public static CombinedFingerprints ParseDelimitedFrom(global::System.IO.Stream input) {
        return CreateBuilder().MergeDelimitedFrom(input).BuildParsed();
      }
      public static CombinedFingerprints ParseDelimitedFrom(global::System.IO.Stream input, pb::ExtensionRegistry extensionRegistry) {
        return CreateBuilder().MergeDelimitedFrom(input, extensionRegistry).BuildParsed();
      }
      public static CombinedFingerprints ParseFrom(pb::ICodedInputStream input) {
        return ((Builder) CreateBuilder().MergeFrom(input)).BuildParsed();
      }
      public static CombinedFingerprints ParseFrom(pb::ICodedInputStream input, pb::ExtensionRegistry extensionRegistry) {
        return ((Builder) CreateBuilder().MergeFrom(input, extensionRegistry)).BuildParsed();
      }
      private CombinedFingerprints MakeReadOnly() {
        return this;
      }
      
      public static Builder CreateBuilder() { return new Builder(); }
      public override Builder ToBuilder() { return CreateBuilder(this); }
      public override Builder CreateBuilderForType() { return new Builder(); }
      public static Builder CreateBuilder(CombinedFingerprints prototype) {
        return new Builder(prototype);
      }
      
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
      public sealed partial class Builder : pb::GeneratedBuilder<CombinedFingerprints, Builder> {
        protected override Builder ThisBuilder {
          get { return this; }
        }
        public Builder() {
          result = DefaultInstance;
          resultIsReadOnly = true;
        }
        internal Builder(CombinedFingerprints cloneFrom) {
          result = cloneFrom;
          resultIsReadOnly = true;
        }
        
        private bool resultIsReadOnly;
        private CombinedFingerprints result;
        
        private CombinedFingerprints PrepareBuilder() {
          if (resultIsReadOnly) {
            CombinedFingerprints original = result;
            result = new CombinedFingerprints();
            resultIsReadOnly = false;
            MergeFrom(original);
          }
          return result;
        }
        
        public override bool IsInitialized {
          get { return result.IsInitialized; }
        }
        
        protected override CombinedFingerprints MessageBeingBuilt {
          get { return PrepareBuilder(); }
        }
        
        public override Builder Clear() {
          result = DefaultInstance;
          resultIsReadOnly = true;
          return this;
        }
        
        public override Builder Clone() {
          if (resultIsReadOnly) {
            return new Builder(result);
          } else {
            return new Builder().MergeFrom(result);
          }
        }
        
        public override pbd::MessageDescriptor DescriptorForType {
          get { return global::libsignal.fingerprint.FingerprintProtos.CombinedFingerprints.Descriptor; }
        }
        
        public override CombinedFingerprints DefaultInstanceForType {
          get { return global::libsignal.fingerprint.FingerprintProtos.CombinedFingerprints.DefaultInstance; }
        }
        
        public override CombinedFingerprints BuildPartial() {
          if (resultIsReadOnly) {
            return result;
          }
          resultIsReadOnly = true;
          return result.MakeReadOnly();
        }
        
        public override Builder MergeFrom(pb::IMessage other) {
          if (other is CombinedFingerprints) {
            return MergeFrom((CombinedFingerprints) other);
          } else {
            base.MergeFrom(other);
            return this;
          }
        }
        
        public override Builder MergeFrom(CombinedFingerprints other) {
          if (other == global::libsignal.fingerprint.FingerprintProtos.CombinedFingerprints.DefaultInstance) return this;
          PrepareBuilder();
          if (other.HasVersion) {
            Version = other.Version;
          }
          if (other.HasLocalFingerprint) {
            MergeLocalFingerprint(other.LocalFingerprint);
          }
          if (other.HasRemoteFingerprint) {
            MergeRemoteFingerprint(other.RemoteFingerprint);
          }
          this.MergeUnknownFields(other.UnknownFields);
          return this;
        }
        
        public override Builder MergeFrom(pb::ICodedInputStream input) {
          return MergeFrom(input, pb::ExtensionRegistry.Empty);
        }
        
        public override Builder MergeFrom(pb::ICodedInputStream input, pb::ExtensionRegistry extensionRegistry) {
          PrepareBuilder();
          pb::UnknownFieldSet.Builder unknownFields = null;
          uint tag;
          string field_name;
          while (input.ReadTag(out tag, out field_name)) {
            if(tag == 0 && field_name != null) {
              int field_ordinal = global::System.Array.BinarySearch(_combinedFingerprintsFieldNames, field_name, global::System.StringComparer.Ordinal);
              if(field_ordinal >= 0)
                tag = _combinedFingerprintsFieldTags[field_ordinal];
              else {
                if (unknownFields == null) {
                  unknownFields = pb::UnknownFieldSet.CreateBuilder(this.UnknownFields);
                }
                ParseUnknownField(input, unknownFields, extensionRegistry, tag, field_name);
                continue;
              }
            }
            switch (tag) {
              case 0: {
                throw pb::InvalidProtocolBufferException.InvalidTag();
              }
              default: {
                if (pb::WireFormat.IsEndGroupTag(tag)) {
                  if (unknownFields != null) {
                    this.UnknownFields = unknownFields.Build();
                  }
                  return this;
                }
                if (unknownFields == null) {
                  unknownFields = pb::UnknownFieldSet.CreateBuilder(this.UnknownFields);
                }
                ParseUnknownField(input, unknownFields, extensionRegistry, tag, field_name);
                break;
              }
              case 8: {
                result.hasVersion = input.ReadUInt32(ref result.version_);
                break;
              }
              case 18: {
                global::libsignal.fingerprint.FingerprintProtos.LogicalFingerprint.Builder subBuilder = global::libsignal.fingerprint.FingerprintProtos.LogicalFingerprint.CreateBuilder();
                if (result.hasLocalFingerprint) {
                  subBuilder.MergeFrom(LocalFingerprint);
                }
                input.ReadMessage(subBuilder, extensionRegistry);
                LocalFingerprint = subBuilder.BuildPartial();
                break;
              }
              case 26: {
                global::libsignal.fingerprint.FingerprintProtos.LogicalFingerprint.Builder subBuilder = global::libsignal.fingerprint.FingerprintProtos.LogicalFingerprint.CreateBuilder();
                if (result.hasRemoteFingerprint) {
                  subBuilder.MergeFrom(RemoteFingerprint);
                }
                input.ReadMessage(subBuilder, extensionRegistry);
                RemoteFingerprint = subBuilder.BuildPartial();
                break;
              }
            }
          }
          
          if (unknownFields != null) {
            this.UnknownFields = unknownFields.Build();
          }
          return this;
        }
        
        
        public bool HasVersion {
          get { return result.hasVersion; }
        }
        [global::System.CLSCompliant(false)]
        public uint Version {
          get { return result.Version; }
          set { SetVersion(value); }
        }
        [global::System.CLSCompliant(false)]
        public Builder SetVersion(uint value) {
          PrepareBuilder();
          result.hasVersion = true;
          result.version_ = value;
          return this;
        }
        public Builder ClearVersion() {
          PrepareBuilder();
          result.hasVersion = false;
          result.version_ = 0;
          return this;
        }
        
        public bool HasLocalFingerprint {
         get { return result.hasLocalFingerprint; }
        }
        public global::libsignal.fingerprint.FingerprintProtos.LogicalFingerprint LocalFingerprint {
          get { return result.LocalFingerprint; }
          set { SetLocalFingerprint(value); }
        }
        public Builder SetLocalFingerprint(global::libsignal.fingerprint.FingerprintProtos.LogicalFingerprint value) {
          pb::ThrowHelper.ThrowIfNull(value, "value");
          PrepareBuilder();
          result.hasLocalFingerprint = true;
          result.localFingerprint_ = value;
          return this;
        }
        public Builder SetLocalFingerprint(global::libsignal.fingerprint.FingerprintProtos.LogicalFingerprint.Builder builderForValue) {
          pb::ThrowHelper.ThrowIfNull(builderForValue, "builderForValue");
          PrepareBuilder();
          result.hasLocalFingerprint = true;
          result.localFingerprint_ = builderForValue.Build();
          return this;
        }
        public Builder MergeLocalFingerprint(global::libsignal.fingerprint.FingerprintProtos.LogicalFingerprint value) {
          pb::ThrowHelper.ThrowIfNull(value, "value");
          PrepareBuilder();
          if (result.hasLocalFingerprint &&
              result.localFingerprint_ != global::libsignal.fingerprint.FingerprintProtos.LogicalFingerprint.DefaultInstance) {
              result.localFingerprint_ = global::libsignal.fingerprint.FingerprintProtos.LogicalFingerprint.CreateBuilder(result.localFingerprint_).MergeFrom(value).BuildPartial();
          } else {
            result.localFingerprint_ = value;
          }
          result.hasLocalFingerprint = true;
          return this;
        }
        public Builder ClearLocalFingerprint() {
          PrepareBuilder();
          result.hasLocalFingerprint = false;
          result.localFingerprint_ = null;
          return this;
        }
        
        public bool HasRemoteFingerprint {
         get { return result.hasRemoteFingerprint; }
        }
        public global::libsignal.fingerprint.FingerprintProtos.LogicalFingerprint RemoteFingerprint {
          get { return result.RemoteFingerprint; }
          set { SetRemoteFingerprint(value); }
        }
        public Builder SetRemoteFingerprint(global::libsignal.fingerprint.FingerprintProtos.LogicalFingerprint value) {
          pb::ThrowHelper.ThrowIfNull(value, "value");
          PrepareBuilder();
          result.hasRemoteFingerprint = true;
          result.remoteFingerprint_ = value;
          return this;
        }
        public Builder SetRemoteFingerprint(global::libsignal.fingerprint.FingerprintProtos.LogicalFingerprint.Builder builderForValue) {
          pb::ThrowHelper.ThrowIfNull(builderForValue, "builderForValue");
          PrepareBuilder();
          result.hasRemoteFingerprint = true;
          result.remoteFingerprint_ = builderForValue.Build();
          return this;
        }
        public Builder MergeRemoteFingerprint(global::libsignal.fingerprint.FingerprintProtos.LogicalFingerprint value) {
          pb::ThrowHelper.ThrowIfNull(value, "value");
          PrepareBuilder();
          if (result.hasRemoteFingerprint &&
              result.remoteFingerprint_ != global::libsignal.fingerprint.FingerprintProtos.LogicalFingerprint.DefaultInstance) {
              result.remoteFingerprint_ = global::libsignal.fingerprint.FingerprintProtos.LogicalFingerprint.CreateBuilder(result.remoteFingerprint_).MergeFrom(value).BuildPartial();
          } else {
            result.remoteFingerprint_ = value;
          }
          result.hasRemoteFingerprint = true;
          return this;
        }
        public Builder ClearRemoteFingerprint() {
          PrepareBuilder();
          result.hasRemoteFingerprint = false;
          result.remoteFingerprint_ = null;
          return this;
        }
      }
      static CombinedFingerprints() {
        object.ReferenceEquals(global::libsignal.fingerprint.FingerprintProtos.Descriptor, null);
      }
    }
    
    #endregion
    
  }
}

#endregion Designer generated code
